// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrecbltntbkkhsztwuaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZWNibHRudGJra2hzenR3dWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTAyMjUsImV4cCI6MjA2OTc2NjIyNX0.Cyo_mmUfBKNVQ4ywLgTxrNz60aib9KXvs0g4j5wsql4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});